-- Server-side secrets that never need to leave Supabase live in Vault:
--   mz_cron_secret     generated here; shared by pg_cron and the send-reminders function
--   mz_vapid_public / mz_vapid_private
--                      generated by send-reminders on first use (Web Push key pair)
--   mz_project_url     https://<ref>.supabase.co — set once after applying:
--                      select vault.create_secret('https://<ref>.supabase.co', 'mz_project_url');
-- Only GEMINI_API_KEY (and other AI keys) come from the environment — they are
-- synced from GitHub Actions secrets by .github/workflows/deploy-supabase.yml.

create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;

-- Edge functions (service role only) read/write mz_* vault secrets through these.
create or replace function public.mz_get_secret(secret_name text)
returns text language sql stable security definer set search_path = '' as $$
  select decrypted_secret from vault.decrypted_secrets
  where name = secret_name and left(secret_name, 3) = 'mz_'
  limit 1
$$;

create or replace function public.mz_set_secret(secret_name text, secret_value text)
returns void language plpgsql security definer set search_path = '' as $$
declare existing uuid;
begin
  if left(secret_name, 3) <> 'mz_' then
    raise exception 'only mz_ secrets';
  end if;
  select id into existing from vault.secrets where name = secret_name;
  if existing is null then
    perform vault.create_secret(secret_value, secret_name);
  else
    perform vault.update_secret(existing, secret_value);
  end if;
end $$;

revoke all on function public.mz_get_secret(text) from public, anon, authenticated;
revoke all on function public.mz_set_secret(text, text) from public, anon, authenticated;
grant execute on function public.mz_get_secret(text) to service_role;
grant execute on function public.mz_set_secret(text, text) to service_role;

do $$
begin
  if not exists (select 1 from vault.secrets where name = 'mz_cron_secret') then
    perform vault.create_secret(encode(extensions.gen_random_bytes(32), 'hex'), 'mz_cron_secret');
  end if;
end $$;

-- Every 15 minutes: the function sends at most one reminder per user per local day,
-- at/after their reminder time (default 21:30), skipping users who logged this evening.
select cron.schedule(
  'mz-daily-reminders',
  '*/15 * * * *',
  $$
  select net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name = 'mz_project_url') || '/functions/v1/send-reminders',
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'mz_cron_secret')
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 20000
  )
  where exists (select 1 from vault.decrypted_secrets where name = 'mz_project_url');
  $$
);
